# =========================================================================
# QUTEBROWSER CONFIGURATION
# =========================================================================
# pylint: disable=C0111
c = c  # noqa: F821 pylint: disable=E0602,C0103
config = config  # noqa: F821 pylint: disable=E0602,C0103

import sys
import os

# -------------------------------------------------------------------------
# IMPORTS & INITIAL SETUP
# -------------------------------------------------------------------------

# Load settings configured via the GUI
config.load_autoconfig()

# Allow importing from the current directory
sys.path.append(os.path.dirname(__file__))

# Load colors generated by Matugen
try:
    from matugen_colors_qutebrowser import colors as matugen
except ImportError:
    matugen = {"background": "#000000", "foreground": "#ffffff"}

# Load private settings if they exist
try:
    from .private import *
except ImportError:
    pass

# -------------------------------------------------------------------------
# THEMING & COLORS
# -------------------------------------------------------------------------

# Statusbar
c.colors.statusbar.command.fg = matugen["foreground"]
c.colors.statusbar.normal.fg = matugen["secondary_container"]
c.colors.statusbar.passthrough.fg = matugen["secondary_container"]
c.colors.statusbar.url.fg = matugen["error"]
c.colors.statusbar.url.success.https.fg = matugen["primary"]
c.colors.statusbar.url.hover.fg = matugen["tertiary_container"]

# Tabs
c.colors.tabs.even.bg = "#00000000"
c.colors.tabs.odd.bg = "#00000000"
c.colors.tabs.even.fg = matugen["foreground"]
c.colors.tabs.odd.fg = matugen["foreground"]
c.colors.tabs.selected.even.bg = matugen["primary"]
c.colors.tabs.selected.odd.bg = matugen["secondary"]
c.colors.tabs.selected.even.fg = matugen["on_primary"]
c.colors.tabs.selected.odd.fg = matugen["on_primary"]

# Completion Menu
c.colors.completion.item.selected.match.fg = matugen["primary_container"]
c.colors.completion.match.fg = matugen["primary_container"]
c.colors.completion.odd.bg = matugen["background"]
c.colors.completion.even.bg = matugen["background"]
c.colors.completion.fg = matugen["foreground"]

# Hints & Messages
c.colors.hints.bg = matugen["background"]
c.colors.hints.fg = matugen["foreground"]
c.colors.messages.info.bg = matugen["background"]
c.colors.messages.info.fg = matugen["foreground"]

# Dark Mode for Webpages
c.colors.webpage.darkmode.enabled = False
c.colors.webpage.darkmode.algorithm = "lightness-cielab"
c.colors.webpage.darkmode.policy.images = "never"

# Window Transparency
c.window.transparent = True

# -------------------------------------------------------------------------
# FONTS
# -------------------------------------------------------------------------

c.fonts.default_family = []
c.fonts.default_size = "13pt"
c.fonts.web.size.default = 20
c.fonts.web.family.fixed = "monospace"
c.fonts.web.family.sans_serif = "monospace"
c.fonts.web.family.serif = "monospace"
c.fonts.web.family.standard = "monospace"
c.fonts.tabs.selected = "10pt monospace"
c.fonts.tabs.unselected = "9pt monospace"

# -------------------------------------------------------------------------
# TABS
# -------------------------------------------------------------------------

c.tabs.show = "multiple"
c.tabs.title.format = "{audio}{current_title}"
c.tabs.padding = {"top": 0, "bottom": 0, "left": 0, "right": 0}
c.tabs.indicator.width = 0  # No tab indicators
c.tabs.min_width = 1

# -------------------------------------------------------------------------
# URLS & SEARCH ENGINES
# -------------------------------------------------------------------------

c.url.searchengines = {
    "DEFAULT": "https://www.google.com/search?q={}",
    "!aw": "https://wiki.archlinux.org/?search={}",
    "!apkg": "https://archlinux.org/packages/?sort=&q={}&maintainer=&flagged=",
    "!gh": "https://github.com/search?o=desc&q={}&s=stars",
    "!yt": "https://www.youtube.com/results?search_query={}",
}

# -------------------------------------------------------------------------
# COMPLETION & SESSION
# -------------------------------------------------------------------------

c.completion.open_categories = [
    "searchengines",
    "quickmarks",
    "bookmarks",
    "history",
    "filesystem",
]
c.auto_save.session = False  # Save tabs on quit/restart

# -------------------------------------------------------------------------
# BEHAVIOR
# -------------------------------------------------------------------------

c.input.insert_mode.auto_leave = True
c.input.insert_mode.auto_enter = True

# -------------------------------------------------------------------------
# KEYBINDINGS
# -------------------------------------------------------------------------

config.bind("=", "cmd-set-text -s :open")
config.bind("h", "history")
config.bind("cs", "cmd-set-text -s :config-source")
config.bind("tH", "config-cycle tabs.show multiple never")
config.bind("sH", "config-cycle statusbar.show always never")
config.bind("tT", "config-cycle tabs.position top left")
config.bind("T", "hint links tab")
config.bind("pP", "open -- {primary}")
config.bind("pp", "open -- {clipboard}")
config.bind("pt", "open -t -- {clipboard}")
config.bind("qm", "macro-record")
config.bind("<ctrl-y>", "spawn --userscript ytdl.sh")
config.bind("J", "tab-prev")
config.bind("K", "tab-next")
config.bind("gJ", "tab-move -")
config.bind("gK", "tab-move +")
config.bind("gm", "tab-move")

# -------------------------------------------------------------------------
# PRIVACY & SECURITY
# -------------------------------------------------------------------------

config.set("content.webgl", False, "*")
config.set("content.canvas_reading", False)
config.set("content.geolocation", False)
config.set("content.webrtc_ip_handling_policy", "default-public-interface-only")
config.set("content.cookies.accept", "all")
config.set("content.cookies.store", True)
c.content.headers.user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"



# -------------------------------------------------------------------------
# CONTENT BLOCKING
# -------------------------------------------------------------------------

c.content.blocking.enabled = True
c.content.blocking.method = "adblock"  # Requires python-adblock package
c.content.blocking.adblock.lists = [
    "https://github.com/ewpratten/youtube_ad_blocklist/blob/master/blocklist.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/legacy.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/filters.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/filters-2020.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/filters-2021.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/filters-2022.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/filters-2023.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/filters-2024.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/badware.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/privacy.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/badlists.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/annoyances.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/annoyances-cookies.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/annoyances-others.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/badlists.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/quick-fixes.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/resource-abuse.txt",
    "https://github.com/uBlockOrigin/uAssets/raw/master/filters/unbreak.txt",
]

# -------------------------------------------------------------------------
# EXTERNAL APPLICATIONS
# -------------------------------------------------------------------------

c.editor.command = ["alacritty", "-e", "nvim", "+{line} | normal {column0}l", "{file}"]
